version: '3'
services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    volumes:
      - "$PWD:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD:/opt/selenoid/video"
      - "$PWD:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD
    command: ["-conf", "-vnc", "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
    ports:
      - "4444:4444"
  selenoid-ui:
    image: "aerokube/selenoid-ui:latest-release"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8090:8090"
    command: ["--selenoid-uri", "http://selenoid:5432"]
  chrome:
    image: "selenoid/vnc:chrome_80.0"
    network_mode: bridge
    links:
      - selenoid
  video:
    image: "selenoid/video-recorder:latest-release"
    network_mode: bridge
    links:
      - selenoid